[package]
name = "copyxross"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local-ip-address = "0.6.3"
objc = "0.2.7"
cocoa = "0.24.0"
